name: test

on:
  push:

jobs:
  build:
    name: Build for windows
    runs-on: windows-latest
    steps:

      # 1. checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. configure cmake
      - name: Configure CMake
        uses: lukka/get-cmake@latest

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: echo "Running tests ..."