name: test

on:
  push:

jobs:
  build:
    name: Build for windows
    runs-on: windows-latest
    steps:

      # 1. checkout
      -uses: actions/checkout@v4

      -uses: lukka/get-cmake@latest

      -name: Confgure CMake
        run: cmake -S . -B build

      -name: Build
        run: cmake --build build --config Release

      -name: Run tests
        run: echo "Running tests ..."